# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GDTJXxBgrZkQyjReRL7c1uFrJvk5pM7j
"""

from flask import Flask, render_template, request, jsonify
import joblib
import numpy as np
import re
import urllib.parse

app = Flask(__name__)

# Load model, scaler, feature names
model        = joblib.load("best_model.pkl")
scaler       = joblib.load("scaler.pkl")
feature_names = joblib.load("feature_names.pkl")

# ── Feature extraction from URL ──────────────────────────────────────────────

def having_ip_address(url):
    match = re.search(r'\d+\.\d+\.\d+\.\d+', url)
    return -1 if match else 1

def url_length(url):
    if len(url) < 54: return 1
    if len(url) <= 75: return 0
    return -1

def shortening_service(url):
    pattern = r'bit\.ly|goo\.gl|shorte\.st|go2l\.ink|x\.co|ow\.ly|tinyurl|tr\.im|is\.gd|cli\.gs|yfrog\.com|migre\.me|ff\.im|tiny\.cc|url4\.eu|twit\.ac|su\.pr|twurl\.nl|snipurl\.com|short\.to|BudURL\.com|ping\.fm|post\.ly|Just\.as|bkite\.com|snipr\.com|fic\.kr|loopt\.us|doiop\.com|short\.ie|kl\.am|wp\.me|rubyurl\.com|om\.ly|to\.ly|bit\.do|t\.co|lnkd\.in|db\.tt|qr\.ae|adf\.ly|bitly\.com|cur\.lv|tinyurl\.com|ow\.ly|bit\.ly|adcrun\.ch|zpag\.es|short\.cm'
    return -1 if re.search(pattern, url) else 1

def having_at_symbol(url):
    return -1 if '@' in url else 1

def double_slash_redirecting(url):
    # Check after protocol
    pos = url.rfind('//')
    return -1 if pos > 7 else 1

def prefix_suffix(url):
    try:
        domain = urllib.parse.urlparse(url).netloc
        return -1 if '-' in domain else 1
    except:
        return -1

def having_sub_domain(url):
    try:
        netloc = urllib.parse.urlparse(url).netloc
        dots = netloc.count('.')
        if dots == 1: return 1
        if dots == 2: return 0
        return -1
    except:
        return -1

def ssl_final_state(url):
    return 1 if url.startswith('https') else -1

def domain_registration_length(url):
    # Default: cannot check without WHOIS — return suspicious
    return 0

def favicon(url):
    return 1  # Cannot check without fetching page

def port(url):
    try:
        port = urllib.parse.urlparse(url).port
        return -1 if port and port not in [80, 443] else 1
    except:
        return 1

def https_token(url):
    try:
        domain = urllib.parse.urlparse(url).netloc
        return -1 if 'https' in domain.lower() else 1
    except:
        return 1

def request_url(url):
    return 1  # Cannot check without fetching

def url_of_anchor(url):
    return 0  # Cannot check without fetching

def links_in_tags(url):
    return 0

def sfh(url):
    return 0

def submitting_to_email(url):
    return -1 if 'mailto:' in url.lower() else 1

def abnormal_url(url):
    try:
        netloc = urllib.parse.urlparse(url).netloc
        return 1 if netloc in url else -1
    except:
        return -1

def redirect(url):
    return 1  # Cannot check without fetching

def on_mouseover(url):
    return 1

def right_click(url):
    return 1

def popup_window(url):
    return 1

def iframe(url):
    return 1

def age_of_domain(url):
    return 0  # Cannot check without WHOIS

def dns_record(url):
    return 0

def web_traffic(url):
    return 0

def page_rank(url):
    return 0

def google_index(url):
    return 1

def links_pointing_to_page(url):
    return 0

def statistical_report(url):
    return 1


def extract_features(url):
    """Extract all 30 features from a URL."""
    features = [
        having_ip_address(url),
        url_length(url),
        shortening_service(url),
        having_at_symbol(url),
        double_slash_redirecting(url),
        prefix_suffix(url),
        having_sub_domain(url),
        ssl_final_state(url),
        domain_registration_length(url),
        favicon(url),
        port(url),
        https_token(url),
        request_url(url),
        url_of_anchor(url),
        links_in_tags(url),
        sfh(url),
        submitting_to_email(url),
        abnormal_url(url),
        redirect(url),
        on_mouseover(url),
        right_click(url),
        popup_window(url),
        iframe(url),
        age_of_domain(url),
        dns_record(url),
        web_traffic(url),
        page_rank(url),
        google_index(url),
        links_pointing_to_page(url),
        statistical_report(url),
    ]
    return features


FEATURE_LABELS = {
    "having_IP_Address":         "IP Address in URL",
    "URL_Length":                "URL Length",
    "Shortining_Service":        "URL Shortening Service",
    "having_At_Symbol":          "@ Symbol in URL",
    "double_slash_redirecting":  "Double Slash Redirect",
    "Prefix_Suffix":             "Prefix/Suffix with '-'",
    "having_Sub_Domain":         "Sub Domain Count",
    "SSLfinal_State":            "HTTPS / SSL Certificate",
    "Domain_registeration_length": "Domain Registration Length",
    "Favicon":                   "Favicon Source",
    "port":                      "Non-Standard Port",
    "HTTPS_token":               "HTTPS Token in Domain",
    "Request_URL":               "External Request URLs",
    "URL_of_Anchor":             "Anchor URL",
    "Links_in_tags":             "Links in Tags",
    "SFH":                       "Server Form Handler",
    "Submitting_to_email":       "Submit to Email",
    "Abnormal_URL":              "Abnormal URL",
    "Redirect":                  "Redirect Count",
    "on_mouseover":              "OnMouseOver Event",
    "RightClick":                "Right Click Disabled",
    "popUpWidnow":               "Pop-up Window",
    "Iframe":                    "iFrame Usage",
    "age_of_domain":             "Domain Age",
    "DNSRecord":                 "DNS Record",
    "web_traffic":               "Web Traffic Rank",
    "Page_Rank":                 "PageRank",
    "Google_Index":              "Google Index",
    "Links_pointing_to_page":    "Inbound Links",
    "Statistical_report":        "Statistical Report Flag",
}


@app.route("/")
def index():
    return render_template("index.html")


@app.route("/predict", methods=["POST"])
def predict():
    data = request.get_json()
    url  = data.get("url", "").strip()

    if not url:
        return jsonify({"error": "No URL provided"}), 400

    if not url.startswith(("http://", "https://")):
        url = "http://" + url

    raw_features = extract_features(url)
    X = np.array(raw_features).reshape(1, -1)
    X_scaled = scaler.transform(X)

    prediction  = model.predict(X_scaled)[0]
    probability = model.predict_proba(X_scaled)[0]
    confidence  = round(float(max(probability)) * 100, 1)

    # Label mapping: 0 = phishing (was -1), 1 = legitimate (was 1)
    verdict = "PHISHING" if prediction == 0 else "LEGITIMATE"

    # Build feature breakdown
    feature_breakdown = []
    for fname, fval in zip(feature_names, raw_features):
        label = FEATURE_LABELS.get(fname, fname)

        if verdict == "LEGITIMATE":
            # For legitimate sites, only flag truly suspicious features as RISK
            # minor issues shown as OK to avoid confusing users
            if fval == -1:
                status = "WARN"   # downgrade RISK → WARN for legitimate sites
            else:
                status = "OK"
        else:
            # For phishing sites, show full severity
            if fval == -1:
                status = "RISK"
            elif fval == 0:
                status = "WARN"
            else:
                status = "OK"

        feature_breakdown.append({
            "name":   label,
            "value":  fval,
            "status": status
        })

    # For phishing: show riskiest first; for legitimate: show OK first
    if verdict == "PHISHING":
        feature_breakdown.sort(key=lambda x: (x["status"] == "OK", x["status"] == "WARN"))
    else:
        feature_breakdown.sort(key=lambda x: (x["status"] != "OK"))

    return jsonify({
        "verdict":    verdict,
        "confidence": confidence,
        "url":        url,
        "features":   feature_breakdown[:6]
    })


if __name__ == "__main__":
    app.run(debug=True)